### ISSUE TITLE
AssertionError after qtip-parse

### ISSUE THREAD

**Issue by johanneskoester** [BenLangmead/qtip#7]
I now get the following error with the latest qtip and bwa mem:
```
[M::mem_process_seqs] Processed 228080 reads in 150.005 CPU sec, 18.570 real sec
[main] Version: 0.7.16a-r1187-dirty
[main] CMD: resources/bwa mem -Y -R @RG\tID:tumor\tSM:tumor -t 8 index/hg18/genome reads/simulated.tumor.1.fastq reads/simulated.tumor.2.fastq
[main] Real time: 84641.571 sec; CPU: 676518.508 sec
11/28/17-08:09:35:INFO:  running "/vol/data/prosic/qtip/qtip-parse ifs --  -- mapped-qtip/tmpen20vsc4/input_alignments/tmp -- ../data/hg18.fasta -- mapped-qtip/tmpen20vsc4/input_intermediates/tmp -- mapped-qtip/tmpen20vsc4/tandem_intermediates/tmpinp"
Parsing SAM file "mapped-qtip/tmpen20vsc4/input_alignments/tmp" (seed=0)
Could not write all 80 doubles to record file
Finished parsing SAM
Input model in memory:
  Saved 12123 bad-end templates (out of 12123)
  Saved 84303974 concordant pair templates (out of 84303974)
  Saved 39107 discordant pair templates (out of 39107)
Creating tandem read simulator
  Estimate total number of FASTA bases is a bit less than 3142044k
  Simulating reads...
    Wrote 0 unpaired tandem reads (target=0)
    Wrote 10120 bad-end tandem reads (target=10000)
    Wrote 275166 concordant tandem pairs (target=275451)
    Wrote 9972 discordant tandem pairs (target=10000)
Traceback (most recent call last):
  File "resources/qtip", line 1091, in <module>
    go_profile(vars(_args), _aligner_args, _aligner_unpaired_args, _aligner_paired_args)
  File "resources/qtip", line 1042, in go_profile
    go(args, aligner_args, aligner_unpaired_args, aligner_paired_args)
  File "resources/qtip", line 585, in go
    _do_align_tandem_reads()
  File "resources/qtip", line 527, in _do_align_tandem_reads
    assert _have_unpaired_tandem_reads(pass1_prefix_tan) or _have_paired_tandem_reads(pass1_prefix_tan)
AssertionError
```

**Comment by johanneskoester** [comment]
This one seems to come from a full disk. Sorry for the noise.
